### ISSUE TITLE
more than 1 item of same type in same page

### ISSUE THREAD

**Issue by serdarakkilic** [skyglobal/skycons#20]
There should be a class support for the plugin. its only accepting element id's right now 
a code was something like that would work very nice and save sometime:

```html
<canvas class="clear-day" width="50" height="50">
<canvas class="partly-cloudy-day" width="25" height="25">
<canvas class="clear-day" width="25" height="25">
<canvas class="cloudy" width="25" height="25">
<canvas class="wind" width="25" height="25">
<canvas class="cloudy" width="25" height="25">
```
```javascript
icons = new Skycons({"color": "white","resizeClear": true});
var list  = ["clear-day", "clear-night", "partly-cloudy-day","partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind","fog"],i;
for(i = list.length; i--; ) {icons.set(list[i], list[i]);}
icons.play();
```

**Comment by ekynoxe** [comment]
I'm really unsure what you're asking here.
All this repository provides you is a web-font and the supporting CSS (with classes) to use on your website. This is not a plugin for any other font system or any other library, and  there's not javascript involved other than the build itself.

**Comment by serdarakkilic** [comment]
Actually i have asked that ting before i understand the main purpose of the repository.
I couldn't found any way to delete the issue.
so sorry about that :(
