### ISSUE TITLE
Importing specific icons only

### ISSUE THREAD

**Issue by damnhipster** [skyglobal/skycons#9]
Components need icons. Rather than importing `skycons.scss` and all of the icons with it, they should be able to import the specific icons they need.

I've hacked something together just now and it's possible. I'll flesh it out a bit and send it over if this should be a thing.

**Comment by peter-mouland** [comment]
yeah, it hink having to create an scss for each icon within skycons would be too much work.  If people want only one specific icon, let them do that in their own project.  Think we'll keep this plugin as the full set
